baseurl: "https://danielleeconsulting.com/"
title: Daniel Lee Consulting LLC
author: Nan Xiao
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Daniel Lee Consulting LLC
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Blog
      url: /
      weight: 1
    - name: Author
      url: /about/
      weight: 2
    - name: Consulting
      url: /consulting/
      weight: 3
    # - name: GitHub
    #   url: https://github.com/daniellee70
    #   weight: 4
    - name: LinkedIn
      url: https://www.linkedin.com/in/daniel-lee-data-scientist/
      weight: 5
    - name: Subscribe
      url: /index.xml
      weight: 6

# Add the subscribe button